---
replicas: 1

image:
  repository: stirlingtools/stirling-pdf
  tag: 2.4.4-ultra-lite

strategy:
  type: Recreate

ports:
  - containerPort: 8080
    service: true

# Uses ports from .ports section, if service is true
service:
  enabled: true

volumeMounts:
  - name: config
    mountPath: /configs
    # readOnly: true

volumes:
  - name: config
    emptyDir: {sizeLimit: 2Gi}

# pvc:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi

ingress:
  enabled: true
  authelia: false
  className: "nginx"
  annotations: {}
  tls:
    - secretName: local-wildcard-cert
  hosts:
    - host: pdf.local.{{ .Values.domain }}
      paths:
        - path: /
          pathType: Prefix
