labels: {}
secret:
    stringData:
        OCTOPUS_API_KEY: ENC[AES256_GCM,data:SoG68wonxv+QLqchD9RYo42t8RASJ4qfgVfdkR5IOZs=,iv:UrSmMJ0llcTTuNGetpqPm7cMvzjGJJ1oNx0arK8OZYo=,tag:BQzXM07k2Eh2J+j7RbsyiQ==,type:str]
        OCTOPUS_ELECTRICITY_MPAN: ENC[AES256_GCM,data:XQXDefX7TY2/cCDGuQ==,iv:UIr4OyWzM8CJPmxAlBF0ARA7y4J3sNt0EJdKCBjQBgs=,tag:poE/MSDVq8rV994M9gUCng==,type:str]
        OCTOPUS_ELECTRICITY_SN: ENC[AES256_GCM,data:bA0FCnmfcD2PpA==,iv:VBCisSdx+dmdRPISXWmrVv3np3dW7IGnKfkvR9MKDWE=,tag:iH6XyyuGB4mvrAfStHfNzg==,type:str]
        POSTGRES_HOST: ENC[AES256_GCM,data:6eyWYEXuJQHvMvSTUSzJ/b+7,iv:wHFZ/j2vHyyKtCASSIV3kwLXrU6wkFRf6/E2Ahwv1tw=,tag:MzRviTBKH92Gh+RzvkGuzQ==,type:str]
        POSTGRES_PORT: ENC[AES256_GCM,data:U6CJcQ==,iv:TCm1zozEUd1OJMszH2O5OAsyNPAL+bnbFI5A53iBRkY=,tag:xrDVhgVfQbfZ4Xup1FLA9g==,type:str]
        POSTGRES_USER: ENC[AES256_GCM,data:kxqi+Szs3zHrKA==,iv:00lsnDO4kjxT1gp1Q0ZcRxb8/sVtR0qBO27dLIb4EtE=,tag:uM4mGX5BT8T4p168r7WFew==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:jC1vUXTJxY2u6Dznk4fySZC/gac=,iv:kUWj+xDETDLOsp1mtqAdTAfglPJFi5TcyoX6AUxc99A=,tag:V9RhXr29w2GPx6J91KXPdg==,type:str]
        POSTGRES_DB: ENC[AES256_GCM,data:YZU0bsHa4dewAw==,iv:WFyplvD+InFIK9PR6W+7gC0QM1TTTVI+pQEIvu0QRNQ=,tag:8fVsMKY5RwkZmIMVbvFC5w==,type:str]
cronjobs:
    - name: octo-usage
      schedule: 0 10 * * *
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 1
      successfulJobsHistoryLimit: 1
      backoffLimit: 0
      image:
        repository: ghcr.io/afonsoc12/octo-usage
        tag: latest
        pullPolicy: Always
      restartPolicy: Never
      args:
        - --infer
      resources:
        limits:
            cpu: 50m
            memory: 64Mi
        requests:
            cpu: 50m
            memory: 64Mi
sops:
    lastmodified: "2026-02-15T01:35:52Z"
    mac: ENC[AES256_GCM,data:Wcj2w4iyYjZpjnGQ4nkj8NsUNq3GDjOeKKCAG2UwBoSOiORELCJCzoDP08zb4EZ+WhKW9x/Xa4emmgrpnVL0ZS32x3Bk+OYWYC05pzEQ4U3Krh2wOWNrjGVR3tahbQVhx2L+TH82NlMNv75GyTW+oCvVBLJSwkTkbtcdHrel0q4=,iv:GyhxluSY36jTNYFRU+r3TkilK4FBSo1QKKnWHSv6i6M=,tag:APdxUF1CpWvMwnVsAnwvZg==,type:str]
    pgp:
        - created_at: "2024-07-20T15:01:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAovTKlLtkOb61ceSzA3qPhfaP3SOmVVvc3MKvtei379ZL
            i+w9rF8hEtg4OT6g+Xq91bG4uEzbqWpLtDgEjb/IVhPYH8uP2g0hfyYDXC14eBJc
            JmnC/Wvap6ZSNrRLE5vS6PJ0sQGWgumYyIFw0fAOz1HfwUEHxWK7XbGqWMx/LleV
            PjhZBq+bwQ91ZWb6kYqHVJnXV75RYr1Mv8i/QJQENGU8Baj0km5vqSXbONsJFWqL
            8XWHRchoSEWl9wnvKk5pdWuum23JSt9wRVjqvuGvay8qZaZymPrULPn1fRgoWuJm
            U/Sa6oHY3bG/dcS+2xVmT2cL1aXa2ugo9zy+hEqR9cX3cqei+QhMcLITtASE6O9I
            qdiDIWuxKgUiwYVbwK2zIKov0DVO1Ke39le0/uw1ZKWFIIjWMXjP8Hy94MhyRFtq
            wmqyEUJCr/Log87IWsDvwFwKX3MRauJoGRz8FaskM5wqal8XLmCg6wD4xv9SLxk1
            7R9hE0g0rm7lkebIMEYJznYzrVhbw2g3TcDYzsQIDKxQc4rscFDqS5SA1zc5a267
            G7IXae5BpfeoK9p8orIxEIcex2QWcREiRM7RhUaWQdVj3FklLG7Zl89ptUZL8Wcq
            nF9xPxW9V41wahBIWhP3xUJMFE5dD0CvrXfu1z9L0ovbL25s09b3GXytV5wVVTLU
            ZgEJAhBmRpp9oCQAKxkFmW7b9HteynrVj/Rhkg21cjyWxwcHWVswT1gmcGqd3BNo
            Ca0OOo64LGgVwe/c1WoJgdT7wduQXAVf0jSOMRV0VZW2Y3KWFtgvC0qZWddCKtuy
            ksCHIP058Q==
            =ulOd
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP)$
    version: 3.11.0
