---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest-exporter
  namespace: {{ .Release.Namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:afonsoc12/homelab.git
      targetRevision: HEAD
      path: kubernetes/charts/homelab-svc
      helm:
        valueFiles:
          - secrets://../../apps/values.sops.yaml
          - ../../apps/monitoring/speedtest-exporter/values.yaml
  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: monitoring
