apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ include "external-svc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-svc.labels" . | nindent 4 }}
    kubernetes.io/service-name: {{ include "external-svc.fullname" . }}
addressType: IPv4
endpoints:
  - addresses:
      - {{ tpl ( .Values.server.ip | quote ) $ }}
ports:
  - port: {{ .Values.server.port }}
    protocol: {{ .Values.server.protocol }}
